[program:payease-horizon]
process_name=%(program_name)s
command=php /var/www/payease/artisan horizon
autostart=true
autorestart=true
user=deploy
redirect_stderr=true
stdout_logfile=/var/log/payease/horizon.log
stopwaitsecs=3600
