[program:payease-horizon-worker]
process_name=%(program_name)s_%(process_num)02d
command=php /var/www/payease/current/artisan horizon:work --delay=3 --sleep=3 --tries=3 --timeout=120
autostart=true
autorestart=true
user=deploy
numprocs=4
redirect_stderr=true
stdout_logfile=/var/log/payease/horizon-worker.log
stopwaitsecs=600
